# Generated by Django 3.1.1 on 2020-09-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poza', models.ImageField(blank=True, default='poze/default.png', null=True, upload_to='pictures/')),
                ('pret', models.FloatField()),
                ('descriere', models.TextField()),
                ('stoc', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
