# Generated by Django 3.1.1 on 2020-09-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='nume',
            field=models.CharField(default='', max_length=30),
        ),
    ]
